spring:
  application:
    name: db-dora-jsb

logging:
  level:
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
      keys-to-sanitize: .*password.*,.*secret.*,.*token.*
