spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cbs
    username: dora
    password: dora

springdoc:
  api-docs:
    # For AWS API Gateway
    version: openapi_3_0
  show-actuator: true
